name: 'Nightly Merge'

on:
  push:
    branches:
      - master

jobs:
  nightly-merge:

    runs-on: ubuntu-latest

    steps:
    - name: Checkout
      uses: actions/checkout@v2

    - name: Nightly Merge
      uses: redrabbitttt/gh-action-nightly-merge@v1.6.0
      with:
        stable_branch: 'master'
        development_branch: 'feature/screen'
        allow_ff: true
      env:
        GITHUB_TOKEN: ${{ secrets.SS }}
